language: generic
sudo: required
services:
 - docker
 
 before_install:
  -docker build -t cv/docker-react-f Dockerfile.dev .
  
 script:
  - docker run -e CI=true cv/docker-react npm run test